title: Canvas Layer for AWS Lambda
description: >-
  Cairo backed Mozilla Web Canvas API implementation layer for AWS Lambda.
baseurl: ""
url: ""
twitter_username: charoitel
github_username:  charoitel

theme: minima
plugins:
  - jekyll-feed
