title: Canvas Layer for AWS Lambda
description: >
  Cairo backed Mozilla Web Canvas API implementation layer for AWS Lambda.

author: Charoite Lee and contributors
github_username: charoitel

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
